server:
  port: 8080

spring:
  application:
    name: midnight-backend
  mvc:
    async:
      request-timeout: 300000ms
  jackson:
    serialization:
      INDENT_OUTPUT: true
  web:
    resources:
      static-locations: classpath:/static/
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: ohgiraffers
    password: ohgiraffers

logging:
  level:
    root: INFO
    com.ohgiraffers.midnightback: DEBUG
